### ISSUE TITLE
Remote Cli problem

### ISSUE THREAD

**Issue by marialauracangiano** [precision-sustainable-ag/BenchBot-ImageRepository#9]
The Remote Cli folder wasn't working if we just copied and paste after making changes

**Comment by priyajakhar** [comment]
The reason was that the executable file was being compiled in a 'build' mode which doesn't care of executable dependencies. To resolve the issue, the CMake settings were changed to include 'release' mode in VisualStudioCode and the file was recompiled in the new mode. This allowed transferability of the RemoteCli.exe.
